//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ATS.Inspect.Demo.Login.Properties
{
   [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
   [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
   internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
   {
      [global::System.Configuration.ApplicationScopedSettingAttribute()]
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      [global::System.Configuration.DefaultSettingValueAttribute("https://atsusnb191.ats-global.local:5000")]
      public string SecurityManagerEndpoint
      {
         get
         {
            return ((string)(this["SecurityManagerEndpoint"]));
         }
      }

      [global::System.Configuration.ApplicationScopedSettingAttribute()]
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      [global::System.Configuration.DefaultSettingValueAttribute("1ba93dc2-1462-4005-0b0b-08da1baa2f1e")]
      public string ApplicationId
      {
         get
         {
            return ((string)(this["ApplicationId"]));
         }
      }

      [global::System.Configuration.ApplicationScopedSettingAttribute()]
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      [global::System.Configuration.DefaultSettingValueAttribute("INSPECT")]
      public string ExternalCode
      {
         get
         {
            return ((string)(this["ExternalCode"]));
         }
      }

      [global::System.Configuration.ApplicationScopedSettingAttribute()]
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      [global::System.Configuration.DefaultSettingValueAttribute("2")]
      public int DefaultLoginType
      {
         get
         {
            return Convert.ToInt32(this["DefaultLoginType"]);
         }
      }

      private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

      public static Settings Default
      {
         get
         {
            return defaultInstance;
         }
      }
   }
}
